### ISSUE TITLE
[system] - Registration process for m8a team members

### ISSUE THREAD

**Issue by smolinari** [m8a-io/m8a#402]
We need a registration process which will allow new team member of the m8a team to be added to the system for running m8a. These team members can be of three types:

- [ ] m8a team administrators
- [ ] m8a team developers
- [ ] m8a team members (this is hopefully something we'll have later, for "workers" i.e. staff who aren't developers or administrators)

To accomplish the registration of an m8a team member, the following must be collected by the system

 - username (this will be their m8a.io email address)
 - user email address (will get automatically assigned via the registration process)
 - password (only temp password. User must add own password before entering system, will not be entered in the form to add the user)
 - First Name
 - Last Name
 - Date of Birth
 - Address 
 (more tbd)
 
 
 The following steps must happen in the system before a person is an m8a team member:
 
 - [ ] The initial "entity management" system must be in place. (To be dev'ed: see issue: )  
 - [ ] The form for entering the user must be available  
 - [ ] Upon entering the form, the system must check for correct data input (To be dev'ed: see issue: ) 
  
 If the data is valid, the system must do the following steps:        
   - [ ] Enter the user data into m8a Auth (Keycloak) i.e register the user.
   - [ ] Make selection of possible "areas" the new user should be able to administer i.e. email, workflows, deploy/ kargo, user admin, m8a admin (rancher/ k8s), etc.  
   - [ ] Enter the same data in the Zeus database for the user i.e. internal permissions for m8a's own business applications.
   - [ ] Enter new email address for user in email system
   - [ ] Send new user email about successful addition as an m8a team member, welcoming him or her, with a link to enter his or her (new) password. 
   - [ ] Upon entering the new password, the user will be logged into the m8a Zeus system.   
          
Scott
